server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/leword}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://leword-db.cttvfqjqyvwa.eu-central-1.rds.amazonaws.com/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:rootroot}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false


